### ISSUE TITLE
Import xml to strtbl issue

### ISSUE THREAD

**Issue by michalss** [Foxxyyy/CodeX.Games.RDR1#17]
Also found out this files cannot be imported back to rpf

```
merchant05_win32.strtbl.xml
mexarmy02_win32.strtbl.xml
rebel05_win32.strtbl.xml
```

```
System.IndexOutOfRangeException: Index was outside the bounds of the array.
   at CodeX.Games.RDR1.Files.StrtblFile.RegisterProperties() in D:\Projects\csharp\__GameTools\_CODEX\CodeX-027\CodeX.Games.RDR1\Files\StrtblFile.cs:line 375
   at CodeX.Games.RDR1.Files.StrtblFile..ctor(String xml) in D:\Projects\csharp\__GameTools\_CODEX\CodeX-027\CodeX.Games.RDR1\Files\StrtblFile.cs:line 38
   at CodeX.Games.RDR1.RPF6.Rpf6FileManager.ConvertFromXml(String xml, String filename, String folder) in D:\Projects\csharp\__GameTools\_CODEX\CodeX-027\CodeX.Games.RDR1\RPF6\Rpf6FileManager.cs:line 353
   at CodeX.Forms.Explorer.ExploreForm.ImportXml(String[] fpaths) in D:\Projects\csharp\__GameTools\_CODEX\CodeX-027\CodeX.Forms\Explorer\ExploreForm.cs:line 2098
   at CodeX.Forms.Explorer.ExploreForm.ImportXmlDialog() in D:\Projects\csharp\__GameTools\_CODEX\CodeX-027\CodeX.Forms\Explorer\ExploreForm.cs:line 2057
   at CodeX.Forms.Explorer.ExploreForm.ListContextImportXmlMenu_Click(Object sender, EventArgs e) in D:\Projects\csharp\__GameTools\_CODEX\CodeX-027\CodeX.Forms\Explorer\ExploreForm.cs:line 4066
   at System.Windows.Forms.ToolStripMenuItem.OnClick(EventArgs e)
   at System.Windows.Forms.ToolStripItem.HandleClick(EventArgs e)
   at System.Windows.Forms.ToolStripItem.HandleMouseUp(MouseEventArgs e)
   at System.Windows.Forms.ToolStrip.OnMouseUp(MouseEventArgs mea)
   at System.Windows.Forms.ToolStripDropDown.OnMouseUp(MouseEventArgs mea)
   at System.Windows.Forms.Control.WmMouseUp(Message& m, MouseButtons button, Int32 clicks)
   at System.Windows.Forms.Control.WndProc(Message& m)
   at System.Windows.Forms.ToolStrip.WndProc(Message& m)
   at System.Windows.Forms.NativeWindow.Callback(HWND hWnd, MessageId msg, WPARAM wparam, LPARAM lparam)
```

**Comment by Foxxyyy** [comment]
Issues fixed in the last update
