### ISSUE TITLE
while trying to save wfd file

### ISSUE THREAD

**Issue by danthespal** [Foxxyyy/CodeX.Games.RDR1#4]
`See the end of this message for details on invoking 
just-in-time (JIT) debugging instead of this dialog box.

************** Exception Text **************
System.ArgumentNullException: Value cannot be null. (Parameter 'bytes')
   at System.ArgumentNullException.Throw(String paramName)
   at System.IO.File.WriteAllBytes(String path, Byte[] bytes)
   at CodeX.Forms.Explorer.TextureForm.SaveTexturePack(Boolean saveas)
   at CodeX.Forms.Explorer.TextureForm.FileSaveAsMenu_Click(Object sender, EventArgs e)
   at System.Windows.Forms.ToolStripMenuItem.OnClick(EventArgs e)
   at System.Windows.Forms.ToolStripItem.HandleClick(EventArgs e)
   at System.Windows.Forms.ToolStripItem.HandleMouseUp(MouseEventArgs e)
   at System.Windows.Forms.ToolStrip.OnMouseUp(MouseEventArgs mea)
   at System.Windows.Forms.ToolStripDropDown.OnMouseUp(MouseEventArgs mea)
   at System.Windows.Forms.Control.WmMouseUp(Message& m, MouseButtons button, Int32 clicks)
   at System.Windows.Forms.Control.WndProc(Message& m)
   at System.Windows.Forms.ScrollableControl.WndProc(Message& m)
   at System.Windows.Forms.ToolStrip.WndProc(Message& m)
   at System.Windows.Forms.Control.ControlNativeWindow.WndProc(Message& m)
   at System.Windows.Forms.NativeWindow.Callback(IntPtr hWnd, WM msg, IntPtr wparam, IntPtr lparam)
`

**Comment by Foxxyyy** [comment]
@danthespal 

From what I see you tried to export the model from the texture editor (inside the model viewer). This error will also happen for other games like GTAV, etc...

If you want to export the model as a binary file, just right-click on the file and click on `Extract Uncompressed`.
Else if you want to export it as an XML file (for maybe using it for Sollumz) click on `Export XML` or open the model then `Export Selection`.

**Comment by danthespal** [comment]
I would like to replace some textures and save the file into the game.

**Comment by Foxxyyy** [comment]
Just export the file as XML and the textures will be included, then re-import.

**Comment by danthespal** [comment]
I should re-import from the explorer? I can't figure out how to put the files back into the game.
